- hosts: localhost
  tasks:
    - name: enable-repositories
      become: true
      become_user: root
      dnf 
    - name: install-packages
      become: true
      become_user: root
      dnf:
        state: latest
        name:
         - i3-gaps
         - 
