- hosts: localhost
  tasks:
    - name: set hostname to f-adora
      ansible.builtin.hostname:
        name: f-adora
        use: systemd

    - name: install dnf-plugins-core
      become: true
      become_user: root
      dnf:
        state: latest
        name: dnf-plugins-core

    - name: enable-rpmfusion-repositories
      become: true
      become_user: root
      dnf:
        state: latest
        name:
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-35.noarch.rpm
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-35.noarch.rpmfusion
        disable_gpg_check: true

      # - name: enable Copr repo for Iosevka fonts
        # become: true
        # become_user: root
        # community.general.copr:
        #   chroot: x86
        #   host: copr.fedorainfracloud.org
        #   state: enabled
        #   name:
        #     - peterwu/iosevka
        #     - oprizal/timeshift

    - name: enable Tailscale repo
      become: true
      become_user: root
      command: "dnf config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo"

    - name: install packages
      become: true
      become_user: root
      dnf:
        state: latest
        name:
          - '@Development Tools'
          - zsh
          - bpytop
          - neofetch
          - terminator
          - i3-gaps
          - polybar
          - dunst
          - cava
          - nautilus
          - vim
          - neovim
          - nodejs
          - npm
            # - iosevka
            # - iosevka-aile
            # - iosevka-ss06
            # - timeshift
          - flatpak
          - obs-studio
          - tailscale

    - name: Add the flathub flatpak repository remote to the user installation
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: install Spotify from flathub repository
      become: true
      become_user: root
      community.general.flatpak:
        remote: flathub
        method: system
        name:
          - com.spotify.Client

    - name: ohmyzsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh
        clone: true
        dest: ~/ohmyzsh
    - name: spicetify
      git:
        repo: https://github.com/spicetify/spicetify-cli
        clone: true
        dest: ~/spicetify-cli
    - name: powercord
      git:
        repo: https://github.com/powercord-org/powercord
        clone: true
        dest: powercord

    - name: install SpaceVim installation script
      command: "curl -sLf https://spacevim.org/install.sh"
